dist: trusty
sudo: required
language: php
php:
  - '7.0'
  - '7.1'
env:
  - MYSQL_SERVER=127.0.0.1 MYSQL_USER=root MYSQL_PASSWORD= MYSQL_DATABASE=demo
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS demo;'
  - mysql -u root --default-character-set=utf8 demo < database/database.sql
before_script:
  - composer self-update
  - composer update
script:
  - env
